# Generated by Django 2.2.5 on 2021-02-09 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 13, 40, 44, 815740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction'),
        ),
    ]
