# Generated by Django 2.2.5 on 2021-02-09 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210209_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 13, 56, 38, 623114, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='auctions.Auction'),
        ),
    ]
