# Generated by Django 2.2.5 on 2021-02-11 22:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210209_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 22, 46, 21, 124965, tzinfo=utc)),
        ),
    ]
